Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.cpus = 2
    end
    boxes = [
      { :name => "server",
        :net => [
             ["192.168.56.10",  2, "255.255.255.0"],
              ]
      },
    ]
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        opts[:net].each do |ipconf|
          config.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2],virtualbox__intnet: ipconf[3])
        end
     end
    end
  end
  
